In [2]:
import numpy as np
import time

In [3]:
arr = np.array([1,2,3,4]) # pass list in array funstion # basics
print(arr,type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [4]:
# time difference b/w list and numpy arrays
# execution performance

#python list
size = 10_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print (f"time taken by py_list : {end-start} seconds")

#numpy arrays
numpy_array = np.array(py_list)
start = time.time()
# vactorization -> no traiversing each element to sqaure , etire list gets squared
sq_array = numpy_array**2
end = time.time()
print (f"time taken numpy array : {end-start} seconds")


time taken by py_list : 1.183223009109497 seconds
time taken numpy array : 0.06533122062683105 seconds


In [12]:
# difference in memory 
import sys
print(f"size of python list = {sys.getsizeof(py_list)* len(py_list)} bytes")
print(f"size of numpy array = {numpy_array.nbytes} bytes")

size of python list = 800000560000000 bytes
size of numpy array = 80000000 bytes


In [4]:
# type of numpy arrays 
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1,type(arr1),arr1.dtype,arr1.shape)

arr2 = np.array([1,2,3,4,5,"hello"]) # will try to convert it in same datatype
print(arr2,type(arr2),arr2.dtype,arr2.shape)

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,type(arr2d),arr2d.dtype,arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'hello'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [6]:
# Creating Numpy arrays
arr1 = np.zeros((3,3),dtype = "int64") # all zeors
print(arr1,type(arr1),arr1.shape)

arr2 = np.ones((3,3),dtype = "int64") # all ones
print(arr2,type(arr2),arr2.shape)

arr3 = np.full((3,3),100,dtype = "int64") # 3x3 matrix of 100
print(arr3,type(arr3),arr3.shape)

arr4 = np.eye((3),dtype = "int64") # identity matrix
print(arr4,type(arr4),arr4.shape)

arr5 = np.arange((0,11,2)) # range(start,end(not included),step)
print(arr5,type(arr5),arr5.shape)

arr6 = np.linspace((1,100,4)) # print 4 equidisance values b/w 1 & 100
print(arr6,type(arr6),arr6.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'> (3, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]] <class 'numpy.ndarray'> (3, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] <class 'numpy.ndarray'> (3, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]] <class 'numpy.ndarray'> (3, 3)


TypeError: arange: scalar arguments expected instead of a tuple.

In [12]:
#Properties of Array

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
float_arr = arr.astype(np.float64)
print(float_arr.dtype,"\n",float_arr)


(3, 3)
9
int64
2
float64 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [29]:
# Operation on array 

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

# reshape
reshaped = arr.reshape(3,2)
print(reshaped,reshaped.shape)

# Flatten
flatten = arr.flatten()
print(flatten,flatten.shape)

# indexing
print(arr[1,2])

#fancy indexing
arr1 = np.array([1,2,3,4,5])
idx = [0,1,2]
print(arr1[idx])

#boolean indexing
print(arr1[arr1%2 == 0]) 

# Slicing
arr2 = np.array([1,2,3,4,5,6,7,8,9])
print(arr2[1:8:2]) #[start,end,step]

# view vs copy

#copy in list
list = [1,2,3,4,5]
sub_list = list[2:5]
print(list,"\n",sub_list)
sub_list[1] = 6 
print(list,"\n",sub_list)

#view in array
sub_arr = arr2[1:6]
print(arr2,"\n",sub_arr)
sub_arr[0] = 200 
print(arr2,"\n",sub_arr)

#copy for view
arrc = arr2
sub_arrc = arrc[1:3]
print(sub_arrc)
sub_arrc[0] = 500
print(sub_arrc,"\n",arrc)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
6
[1 2 3]
[2 4]
[2 4 6 8]
[1, 2, 3, 4, 5] 
 [3, 4, 5]
[1, 2, 3, 4, 5] 
 [3, 6, 5]
[1 2 3 4 5 6 7 8 9] 
 [2 3 4 5 6]
[  1 200   3   4   5   6   7   8   9] 
 [200   3   4   5   6]
[200   3]
[500   3] 
 [  1 500   3   4   5   6   7   8   9]


In [8]:
# Axes in multi-Dimensional arrays

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))

sum_of_rows = np.sum(arr2d, axis = 1) # need first element of each coloumn
sum_of_coloumn = np.sum(arr2d, axis = 0) # need first element of each row

print(f"{sum_of_rows} \n {sum_of_coloumn}")

#slicing using axes

print(arr2d[0:2 , 1:2]) # row to be accesed : 1 to 2 , coloumns : 1


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[ 6 15 24] 
 [12 15 18]
[[2]
 [5]]


In [13]:
# 3d array
arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2x3x2
print(arr3d,arr3d.shape)

#indexing
print (arr3d[0,1,1]) #4
print (arr3d[1,1,0]) #9

#slicing
print (arr3d[:,0,:]) # both first rows:- : as both layes , 0 as oth row , : as both coloumn
print (arr3d[:,:,0]) # both first coloumn

# manipulating values
arr3d[:,0,:] = 99
print(arr3d)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [17]:
# vectorization & broadcasting

arr1 = np.array([1,2,3,4,5])
print(arr1**2)
print(arr1+10)

# broadcasting

arr2 = np.array([7,8,9,4,5,6])
#print(arr1+arr2) # cannot be broadcasted 

arr3 = np.array ([[1,2,3,7,8],[4,5,6,5,6],[7,8,9,4,5]])
print(arr1+arr3) 

[ 1  4  9 16 25]
[11 12 13 14 15]
[[ 2  4  6 11 13]
 [ 5  7  9  9 11]
 [ 8 10 12  8 10]]


In [20]:
# vextor normalization (use case of broadcasting)

arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std = np.std(arr)
normalized_vector = (arr - mean)/std
print(f"{mean}\n{std}\n{normalized_vector}")

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [25]:
# numpy mathematical functions 

# Aggregation fnx

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.median(arr))
print(np.argmin(arr))
print(np.argmax(arr))

# power fnx
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,5))

# log and e fnx
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

# rounding fnx
print(np.round(3.14))
print(np.floor(3.14))
print(np.ceil(3.14))
print(np.trunc(3.14))

#extra
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))




55
3628800
1
10
5.5
2.8722813232690143
8.25
5.5
0
9
[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[     1     32    243   1024   3125   7776  16807  32768  59049 100000]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
3.0
3.0
4.0
3.0
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
